import { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Container,
  Title,
  Text,
  Paper,
  Stack,
  Group,
  Button,
  Box,
  Divider,
} from '@mantine/core';
import { useEmails } from '@/hooks/useEmails';
import IntentBadge from '@/components/IntentBadge';
import ReplyBox from '@/components/ReplyBox';
import EmailSkeleton from '@/components/EmailSkeleton';
import ErrorState from '@/components/ErrorState';
import { formatFullDate } from '@/utils/formatDate';

/**
 * Email detail page — shows full email content, AI summary, and reply composer.
 */
const EmailDetailPage = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { selectedEmail, isLoading, isGeneratingReply, error, fetchEmailById, handleGenerateReply } =
    useEmails();

  useEffect(() => {
    if (id) fetchEmailById(id);
  }, [id]);

  if (isLoading) {
    return (
      <Box style={{ minHeight: '100vh', background: 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)' }}>
        <Container size="md" py="xl">
          <EmailSkeleton />
        </Container>
      </Box>
    );
  }

  if (error) {
    return (
      <Box style={{ minHeight: '100vh', background: 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)' }}>
        <Container size="md" py="xl">
          <ErrorState message={error} onRetry={() => id && fetchEmailById(id)} />
        </Container>
      </Box>
    );
  }

  if (!selectedEmail) return null;

  return (
    <Box
      style={{
        minHeight: '100vh',
        background: 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)',
      }}
    >
      {/* Header */}
      <Box
        py="md"
        px="lg"
        style={{
          borderBottom: '1px solid rgba(148, 163, 184, 0.1)',
          background: 'rgba(15, 23, 42, 0.8)',
          backdropFilter: 'blur(12px)',
          position: 'sticky',
          top: 0,
          zIndex: 100,
        }}
      >
        <Container size="md">
          <Group>
            <Button
              variant="subtle"
              color="gray"
              size="sm"
              onClick={() => navigate('/dashboard')}
            >
              ← Back
            </Button>
          </Group>
        </Container>
      </Box>

      <Container size="md" py="lg">
        <Stack gap="lg">
          {/* Email Header */}
          <Stack gap="xs">
            <Group justify="space-between" wrap="nowrap">
              <Title order={3} style={{ color: '#f8fafc', letterSpacing: '-0.01em' }}>
                {selectedEmail.subject}
              </Title>
              <IntentBadge intent={selectedEmail.intent} />
            </Group>

            <Group gap="xs">
              <Text size="sm" fw={500} style={{ color: '#94a3b8' }}>
                {selectedEmail.sender}
              </Text>
              <Text size="xs" c="dimmed">
                &lt;{selectedEmail.senderEmail}&gt;
              </Text>
            </Group>

            <Text size="xs" c="dimmed">
              {formatFullDate(selectedEmail.timestamp)}
            </Text>
          </Stack>

          {/* AI Summary Section */}
          {/* TODO: This summary is generated by the AI backend. Connect to real AI summarization API. */}
          <Paper
            p="md"
            radius="md"
            style={{
              background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.1), rgba(139, 92, 246, 0.1))',
              border: '1px solid rgba(59, 130, 246, 0.2)',
            }}
          >
            <Stack gap="xs">
              <Group gap="xs">
                <Text size="xs" fw={600} style={{ color: '#93c5fd' }}>
                  ✨ AI Summary
                </Text>
              </Group>
              <Text size="sm" style={{ color: '#cbd5e1' }}>
                {selectedEmail.summary}
              </Text>
            </Stack>
          </Paper>

          <Divider color="rgba(148, 163, 184, 0.1)" />

          {/* Full Email Body */}
          <Paper
            p="md"
            radius="md"
            style={{
              background: 'rgba(30, 41, 59, 0.4)',
              border: '1px solid rgba(148, 163, 184, 0.05)',
            }}
          >
            <Text
              size="sm"
              style={{ color: '#cbd5e1', whiteSpace: 'pre-wrap', lineHeight: 1.7 }}
            >
              {selectedEmail.body}
            </Text>
          </Paper>

          <Divider color="rgba(148, 163, 184, 0.1)" />

          {/* Reply Section */}
          <ReplyBox
            emailId={selectedEmail.id}
            emailSubject={selectedEmail.subject}
            isGenerating={isGeneratingReply}
            onGenerate={handleGenerateReply}
          />
        </Stack>
      </Container>
    </Box>
  );
};

export default EmailDetailPage;
